version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.8"

# Explicitly set the version of Python and its requirements
python:
  install:
    - requirements: docs/requirements.txt

mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: false

